### ISSUE TITLE
Error when starting machine on Qt (OpenGL) and OpenGL 3.0 renderers

### ISSUE THREAD

**Issue by maximus105** [86Box/86BoxManager#103]
**Describe the bug**
When starting the machine from under 86Box Manager, an error window appears. This error window always appears (only on Qt (OpenGL) and OpenGL 3.0 renderers). When starting the machine from under 86Box Manager, if the Qt (Software) renderer is selected, then everything is fine (there is no window with an error).

**Expected behavior**
The error window should not appear when starting the machine from under 86Box Manager on Qt (OpenGL) and OpenGL 3.0 renderers.

**Screenshots**
![2022-02-10_163531](https://user-images.githubusercontent.com/58270614/153432278-42fe56c5-a484-49a5-a88e-7f0b7781c758.png)
![2022-02-10_163557](https://user-images.githubusercontent.com/58270614/153432296-661018bf-13ed-423e-b0ee-6441be9dde10.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.2 x64 Build 3524
 - Build type: regular, old recompiler.
 - 86Box Manager v1.7.2
 - VM config file (86box.cfg)
[86box.zip](https://github.com/86Box/86BoxManager/files/8041872/86box.zip)

**Comment by daviunic** [comment]
This will be fixed in version 1.7.4, to be released shortly.
