### ISSUE TITLE
Logging does not appear to be working. Am I missing something?

### ISSUE THREAD

**Issue by comradesean** [86Box/86BoxManager#106]
Ask away.
I'm enabling logging under advanced settings, but a log file is not created nor populated if pre-created. Am I missing something or is this a deprecated 86box feature?

**Comment by daviunic** [comment]
We'll look into this, generally enabling this option in the Manager should at the very least create the desired file. The amount of logging output you get depends on the logging level you set in code, though.

It would be pretty nice though if I didn't have to ask away and you would fill out the handy bug report template. Things like Manager and 86Box version, location of the log file you set, etc. are all very relevant.

**Comment by comradesean** [comment]
Forgive my ignorance, but I've searched the documentation for 86box and the documentation was nonexistant for logging, the only thing I found in 86box was a log.c file which does not mention how it's activated so I'm a little confused on what or where I would even set logging level for 86box.

As for the rest of the information, it's 
v.1.7.4 86boxManager
v3.3 86box x64 (both debug and non)
The location is on my desktop which I've also tried pre-created (with Everyone/Full Control) and non-existant.
"C:\Users\Sean Streight\Desktop\86box.log"

**Comment by daviunic** [comment]
Logging level is set in 86Box code as originally said, once that's done and logging is also enabled in Manager settings, it should work. Closing this as it's not really a Manager issue.
