### ISSUE TITLE
Harmless error at startup

### ISSUE THREAD

**Issue by winexe0** [86Box/86BoxManager#107]
**Describe the bug**
When 86box Manager launches, it shows a (harmless) error about the .Net Framework. When continue is clicked, 86box Manager works as expected.

**To Reproduce**
1. Launch 86Box 
2. See error.

**Expected behavior**
86box Manager loads without any errors

**Environment (please complete the following information):**
 - Host OS: Windows 11 version 21H2
 - 86Box build number and type 3738 Regular
 - 86Box Manager Version 1.7.4
**Additional context**
This only happened today. I have restarted my computer with no luck. No updates were installed between yesterday and today. I have attached the error log file
[log.txt](https://github.com/86Box/86BoxManager/files/8551212/log.txt)

**Comment by daviunic** [comment]
Based on the log you provided, it seems .NET Framework derped out when creating the XML application settings or some such. Can't reproduce it myself.

**Comment by winexe0** [comment]
Thank you for your help. I deleted the Manager's .config file from AppData and it worked like a charm.
