### ISSUE TITLE
[security] [BUG] Malware detection

### ISSUE THREAD

**Issue by DJBootyShark** [86Box/86BoxManager#108]
**Describe the bug**
 When scanning the zip on VirusTotal MaxSecure reports that the archive contains Trojan.Malware.300983.susgen Certainly a false positive.

EDIT: Scanning the executable shows the same detection but also SecureAge APEX classifies it as malicious.

**To Reproduce**
Upload zip to VirusTotal.

**Expected behavior**
No detections.

**Comment by DJBootyShark** [comment]
Process actions as reported by the sandbox.

![image](https://user-images.githubusercontent.com/68616291/165141670-dd3ef168-c1c7-4d26-a501-e3fc88188bc3.png)

**Comment by daviunic** [comment]
Nothing in the code is explicitly related to that, so whatever is triggering these crapware antiviruses is beyond my control and thus I don't know how this could be fixed.
