### ISSUE TITLE
[Feature] Linux Port

### ISSUE THREAD

**Issue by shakeyourbunny** [86Box/86BoxManager#116]
**Is your feature request related to a problem? Please describe.**
It does not run in Linux.

**Describe the solution you'd like**
Port it to Linux.

**Comment by xafero** [comment]
You could have a look at https://github.com/86Box/86BoxManager/pull/117 or https://github.com/xafero/86BoxManager directly.

Not native of course, but here are my steps to get it to run:

1. Download 86Box-Windows-32 from GitHub releases
2. Create c:\Program Files (x86)\86Box in Wine (--> "cd ~/.wine/drive_c/Program\ Files\ \(x86\)/86Box")
3. Put something here ~/.wine/drive_c/Program Files (x86)/86Box/roms
4. git clone https://github.com/SpudGunMan/segoe-ui-linux && chmod +x install.sh && ./install.sh
5. dotnet build (execute it in Windows 10)
6. mv win-x86 86BoxManager
7. cd ~/.wine/drive_c/86BoxManager && wine 86Manager.exe

In the future, one could port the UI to be GTK-based and then run it directly in Linux. But as long as Windows Forms in involved, this is the way.

**Comment by shakeyourbunny** [comment]
I already bottled up 86BoxManager, but this is not a satisfying solution, as you cannot launch or open the Linux native version of 86box with it.

**Comment by xafero** [comment]
I would have been good for you to actually mention your workaround (using wine-bottle somehow without sharing any details), so that I never even bother to answer you.

**Comment by xafero** [comment]
An early alpha is here: https://github.com/xafero/86BoxManager/releases

**Comment by xafero** [comment]
You could try https://github.com/RetBox/86BoxManagerX/releases

**Comment by 0x6A7232** [comment]
> You could try https://github.com/RetBox/86BoxManagerX/releases

This link works (the early alpha xafero one is now dead, update?)

**Comment by ppvnf** [comment]
xafero fork doesn't recognize 86box appimage

**Comment by DilanRona** [comment]
Neither does the RetBox version. Went so far as to extract the appimage, and still cannot use the linux version of 86Box manager.

**Comment by jelabarre59** [comment]
The 86BoxManagerX doesn't recognize the Flatpak version either.  I have looked for a LinuxMint/Ubuntu DEB package for 86Box but haven't found one yet.  I expect it's some configuration edit I need to do for the Manager's configuration, I'll have to look through how it does it's settings.

**Comment by daviunic** [comment]
Please report this issue in the appropriate repo (https://github.com/RetBox/86BoxManagerX).

**Comment by DilanRona** [comment]
Which would have been nice if it were possible to post an issue there, but as I pointed out last time, there is no way to open an issue on the retbox page.


Also as a workaround on linux systems, try a symbolic link to the binary. AppImages for example can be done with ln -s 86Box-Linux-x86_64-b6000.AppImage 86Box. Hope that helps.

    On Saturday, 16 November 2024 at 20:47:26 GMT+2, David Simunič ***@***.***> wrote:  
 
 


Please report this issue in the appropriate repo (https://github.com/RetBox/86BoxManagerX).

**Comment by DilanRona** [comment]
![image](https://github.com/user-attachments/assets/c73f3c58-e1b8-4294-b2f5-af668b7d337e)

**Comment by daviunic** [comment]
That is unfortunate, but there's nothing that can be done about it here. It's not my code, nor do I participate in it or communicate with the person who wrote it.

I suppose you can drop by the 86Box discord server to see if anyone there can help out with the issue.

**Comment by xafero** [comment]
> That is unfortunate, but there's nothing that can be done about it here. It's not my code, nor do I participate in it or communicate with the person who wrote it.
> 
> I suppose you can drop by the 86Box discord server to see if anyone there can help out with the issue.

Just pretend you did not get any pull request ever. If you ignore stuff, it goes away, I guess.

**Comment by daviunic** [comment]
As you may or may not have noticed, this repo is rarely maintained anymore due to various reasons. I don't intend to make any more major changes to this program, which was originally created as a stopgap solution anyway.

You're free to maintain a fork of course and do as you please with it, but I'm not looking to adopt someone else's major code changes and all the potential issues that come with it, including maintenance. The least you can do in this case is accept responsibility for your own work, accept issues on your fork and help out people that have problems with your code, instead of being rude here. And just maybe update the repo readme too while you're at it, so people don't come to me for problems I have nothing to do with.
