### ISSUE TITLE
When 86Manager.exe is opened SmartScreen shows up[BUG]

### ISSUE THREAD

**Issue by WatStudios** [86Box/86BoxManager#128]
**Describe the bug**
If you double click the app SmartScreen pops up in blue

**To Reproduce**
1. Install the 86boxManager
2. Double Click it
3. SmartScreen pops up

**Expected behavior**
It just runs fine

**Screenshots**
![AeroShot 2_b1](https://github.com/86Box/86BoxManager/assets/159730338/26139ed3-892b-4c25-9f6c-995b28252997)

**Environment (please complete the following information):**
 - Host OS: Windows 10 Pro 22H2 19045.4598
 - 86Box build number: 5634
 - 86Box Manager Version: 1.7.4

**Comment by daviunic** [comment]
There's nothing we can do about this unfortunately, something trips SmartScreen but the program does nothing malicious, as evident in the source code. You can try adding it to your Windows Defender exclusions to see if that helps.

**Comment by WatStudios** [comment]
Oh it's fine I told SmartScreen in the properties of the .exe that it's safe and it's working now
![86Box Manager_b1](https://github.com/86Box/86BoxManager/assets/159730338/8c66c2dd-95a1-4de7-a366-dff3b3ad7594)
