### ISSUE TITLE
Unable to use recommended 86BoxManager for linux

### ISSUE THREAD

**Issue by DilanRona** [86Box/86BoxManager#129]
I tried the recommended 86Box manager for Linux (https://github.com/RetBox/86BoxManagerX), and whichever way I try, It will not recognize the 86Box appimage.

Tried extracting the appimage, used various points in the folder that was created.
Tried renaming the appimage, using 86Box.Appimage, 86box.Appimage, 86Box, and 86box

Only way I can get the manager to work properly is using the windows version, and it is not a long term solution for me.

**Comment by daviunic** [comment]
You should open the issue on that repo, there's nothing Linux-related in this original version and therefore I can't help you with this.

**Comment by DilanRona** [comment]
Tried to do that there. Except there is no way to open the issue on that repo. :-(

**Comment by daviunic** [comment]
Oh sorry, I didn't see that before. I've forwarded this issue to the fork's author.

**Comment by DilanRona** [comment]
Also tried cloning the RetBox repo, and compiling it myself. Not working. Even tried https://github.com/upseguest/86BoxManagerX, same problem.

As of now, I am officially out of ideas, and stuck using windows to manage the 86Box machines.

**Comment by DilanRona** [comment]
Found a solution, thanks to this video here: https://youtu.be/05ftCO9kBFU?t=168

Make a soft link to the 86Box AppImage. The Manager will still report it as an unknown version, but you can then start the vm from Linux, and configure the vm as well.

So this ticket can be considered closed on your end until RetBox can fix it. It would help if you or RetBox could add the softlink command to the 86BoxManager page.

`ln -s 86Box-Linux-x86_64-b6000.AppImage 86Box`
