### ISSUE TITLE
Manager doesn't detect when a VM gets paused directly in 86Box

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86BoxManager#19]
When a VM gets paused directly in 86Box, its status is still `STATUS_RUNNING`. 

Furthermore, when the Manager's pause button is used on such Schrödinger's VM, the status gets updated to `STATUS_PAUSED`, but the machine actually gets unpaused.

**Comment by daviunic** [comment]
This happens because Window Message communication is a one way street apparently. If I could check some return value to see what state the VM is in on the 86Box side, that'd be nice. I'll look into this.

**Comment by daviunic** [comment]
Fixed in 1.1.0. Because this required changes in both Manager and 86Box itself, the minimum required build of 86Box has been increased to 1799.
