### ISSUE TITLE
Freeze after reboot or shutdown machine

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [86Box/86BoxManager#25]
1.1.0 - freeze after reboot or shutdown machine. Tested standalone 86box - its ok.
Tried: hard reset, soft reset (save BIOS and reboot), ctrl+alt+de - same thing.

**Comment by daviunic** [comment]
Which build of 86Box are you using?

**Comment by gandalfthewhite19890404** [comment]
86box - 773b8bfd

**Comment by daviunic** [comment]
Well, I'll need some additional information in that case - which OS are you running this on, .NET Framework version, your manager settings, etc.

Also, please upload the troublesome VM folders someplace so I can do some tests of my own.

Thanks for reporting the issue.

**Comment by gandalfthewhite19890404** [comment]
Manager settings:
![image](https://user-images.githubusercontent.com/24764335/48201657-3b96f980-e37c-11e8-88df-d7dc7af8eac9.png)
VM folder:
[VM1.zip](https://github.com/86Box/86BoxManager/files/2561932/VM1.zip)
Romset - http://tinyurl.com/rs20181008
Windows 10, 1803 with .NET FW 4.7

**Comment by daviunic** [comment]
Thank you. I think the problem may lie more on the 86Box side than the Manager, but I'll have to investigate further. Is the VM you sent me the only one where this happens, or are there any others showing the same problem?

**Comment by gandalfthewhite19890404** [comment]
I has only one VM. But I created another one - same thing.

**Comment by daviunic** [comment]
We believe the problem is related to the ATI Korean VGA card. Can you change only the display card to something else and see if the problem is gone?

**Comment by gandalfthewhite19890404** [comment]
Yes, it fixes an issue. Tested with PCI S3 Virge.
But this bug should be documented as separate issue (or just rename current) - mabe some other GPUs are affected too.

**Comment by daviunic** [comment]
The issue is apparently gone in the latest 86Box build.
