### ISSUE TITLE
[Bug] Configuration not saved when I select generic XT clone PC. 

### ISSUE THREAD

**Issue by Fenix770** [86Box/86BoxManager#29]
Hello!

When I select Generic XT clone, and save, the 86box does not save any data and the configuration is still the default. This bug seems to happen only when I select an XT machine. Also checked this configuration on 86box executable and there is no problem with the config.

Thanks in advance!

**Comment by daviunic** [comment]
I'll look into this soon.

**Comment by Fenix770** [comment]
Host machine: Windows 8.1 x64, 6GB RAM, i5 4210u,  video: intel hd 4400 and Nvidia 820m.
I use the last build of 86box #1830 (november 9).
The bug occurs in 86boxManager 1.1 and 1.2

**Comment by daviunic** [comment]
I need your Manager settings as well...

**Comment by Fenix770** [comment]
Problem Solved!
I deleted the configuration and created a new one. The issue did not appear, any more.

Thanks!

**Comment by daviunic** [comment]
Closing the issue then.
