### ISSUE TITLE
Prepare for a Linux port

### ISSUE THREAD

**Issue by daviunic** [86Box/86BoxManager#5]
Once 86Box gets a Linux port, the Manager should follow suit. Testing and potential modifications should be done to prepare for this eventuality. ETA unknown.

**Comment by telanus** [comment]
With v3.2 of 86Box now having a Linux build, this would be a n useful addition for Linux users. @daviunic @OBattler

**Comment by daviunic** [comment]
The frontend would need to be replaced, as WinForms is still Windows-only. It's out of scope for version 2.0 though, so it'll probably have to be done by someone else (if ever).
