### ISSUE TITLE
Allow selecting multiple VMs

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86BoxManager#50]
This is useful for bulk starting, stopping, resetting or deleting multiple VMs. VirtualBox does support this and they disable menu items for move, clone, settings that trigger a UI when multiple VMs are selected.

**Comment by daviunic** [comment]
Will be done in version 1.6.

**Comment by daviunic** [comment]
A problem with this is when you select VMs with different statuses - how to handle the start/stop button etc.

**Comment by daviunic** [comment]
Implemented in 1.6.0 for delete, kill, wipe, open folder and create shortcut operations. More operations might be supported for multiselect in the future.
