### ISSUE TITLE
Idea: Make an installer

### ISSUE THREAD

**Issue by daemonspudguy** [86Box/86BoxManager#57]
Hi! I would like to have an installer program for 86Box Manager that also downloads 86Box. I would help, but my coding skills don't exist yet.

**Comment by daviunic** [comment]
I'll consider this for a future major release.

**Comment by daemonspudguy** [comment]
86box 2.0 is out.

**Comment by daviunic** [comment]
The milestones on this repo are for the Manager, not 86Box. So v2.0 of Manager, ETA for which is currently unknown.

**Comment by daemonspudguy** [comment]
@daviunic Why was this idea removed from the 2.0 milestone?

**Comment by daviunic** [comment]
Pushed back since it probably won't be done for 2.0.
