### ISSUE TITLE
125% scaling issues in Windows 8.1

### ISSUE THREAD

**Issue by SigmaTel71** [86Box/86BoxManager#58]
All the text is garbled in buttons and checkboxes.
![image](https://user-images.githubusercontent.com/17989678/61877153-15f45500-aef7-11e9-955c-cffe644b34fb.png)
![image](https://user-images.githubusercontent.com/17989678/61877170-1ee52680-aef7-11e9-8fdf-def188cdf0c3.png)

**Comment by daviunic** [comment]
I'll look into this, I think I know how to make it DPI-aware.

**Comment by daviunic** [comment]
Please try this build and let me know if it fixes the issue.
[86BoxManager_1.5.2.zip](https://github.com/86Box/86BoxManager/files/3433137/86BoxManager_1.5.2.zip)

**Comment by SigmaTel71** [comment]
![image](https://user-images.githubusercontent.com/17989678/61906015-19a5cd00-af33-11e9-9791-e77d7c04307e.png)
![image](https://user-images.githubusercontent.com/17989678/61906026-1f031780-af33-11e9-817d-5c0dcd5e69c1.png)
Fixed! Issue is being closed.

**Comment by daviunic** [comment]
Whoops, thought I closed the issue by mistake in my previous reply before I saw yours.
