### ISSUE TITLE
Incorrect error appears when configuring VM while 86Box path is invalid

### ISSUE THREAD

**Issue by eggleston1** [86Box/86BoxManager#60]
If the path to 86Box isn't correct and you try to configure a VM, it'll produce an error stating "This virtual machine could not be started." followed by an Exception message:

![86Man](https://user-images.githubusercontent.com/31838395/63632215-2edc4d00-c600-11e9-9fb7-1d2c1bc0fdc0.PNG)

I realized after going through Settings that 86BoxManager uses a path to locate 86Box rather than just being in the same directory (I had unzipped the two into a desktop folder). It would be beneficial to new users to either **1)** update this error to match the same error displayed when trying to start a VM ("Cannot find 86Box.exe. Make sure your settings are correct and try again.") or **2)** you could also check if 86Box.exe exists in C:\Program Files (x86)\86Box\ and then set the path as such otherwise prompt the user for it's location on startup.

**Comment by daviunic** [comment]
I'll update the error message to match the one for starting a VM.

**Comment by daviunic** [comment]
The error message has been changed in 1.5.4.
