### ISSUE TITLE
Import VM path still required after unchecking

### ISSUE THREAD

**Issue by eggleston1** [86Box/86BoxManager#61]
When creating a new VM, if you check the box for "Import VM files from:" and then uncheck it again it still produces the error: "If you wish to import VM files, you must specify a path."

![Capture](https://user-images.githubusercontent.com/31838395/63632729-d5791b80-c609-11e9-9b29-a5822d2225dd.PNG)

**Comment by daviunic** [comment]
Confirmed in 1.5.2, will be fixed.

**Comment by daviunic** [comment]
Fixed in 1.5.4. I was always setting a bool to true on checked_changed event instead of negating it...
