### ISSUE TITLE
Update disk images path when import

### ISSUE THREAD

**Issue by kkwpsv** [86Box/86BoxManager#65]
When importing vm, there's a message to update path. I usually save disk images at same directory with cfg. Images will be copied, but I need to update the path manually. I think the path should be updated  automatically in this situation. And I'll be glad to implement this function if you agree.

**Comment by dhrdlicka** [comment]
This is related to 86Box#195.

**Comment by daviunic** [comment]
This should be solved on the 86Box side, really. Modifying the cfg on the Manager side as well can create more problems than it solves, hence why I avoided it so far and would prefer to avoid it still.

**Comment by kkwpsv** [comment]
OK. If I can, I may try to help. But I'm not so good at C as C#...

**Comment by daviunic** [comment]
Thank you. First we have to discuss with OBattler who maintains 86Box, but stay in touch if you wish to help out.
