### ISSUE TITLE
Configuration presets

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86BoxManager#72]
It might not be a bad idea to provide some ready configuration presets for common workloads.

**Comment by daviunic** [comment]
You mean config presets for the Manager or 86Box?

**Comment by dhrdlicka** [comment]
I mean 86Box config presets of course

**Comment by daviunic** [comment]
Good idea actually. Could be done before v2.0 even.

**Comment by daviunic** [comment]
Delayed to version 2.0 until the implementation details are worked out.

**Comment by daviunic** [comment]
Idea dropped, out of scope for 2.0. as it stands currently.
