### ISSUE TITLE
Shift of the settings window 86Box

### ISSUE THREAD

**Issue by maximus105** [86Box/86BoxManager#78]
An BUG was discovered: when the "Configure" button is pressed in 86Box Manager screens, the settings window 86Box is constantly shifted to the upper left corner of the screen. Can I fix this somehow?

**Comment by daviunic** [comment]
> Can I fix this somehow?

No. It needs to be looked into on both 86Box and Manager side and fixed.

**Comment by daviunic** [comment]
This is not a Manager problem, but an 86Box problem instead.
