### ISSUE TITLE
VM Config File ignored

### ISSUE THREAD

**Issue by RCcola1987** [86Box/86BoxManager#80]
After moving my VM folder and telling 86Box Manager where it is the saved config is not loaded. There is a config file with the correct information in it in the VM folder but the Manager does not load the config and sets the VM back to default settings.

This is with the newest versions of both Manager and 86Box.

**Comment by daviunic** [comment]
The Manager doesn't load anything, it just passes the path of the config file to the emulator when starting a VM. See [this wiki page](https://github.com/86Box/86BoxManager/wiki/Changing-your-virtual-machines-folder) for more information.

Current behaviour is not exactly optimal, so I'll look at how to improve this in a future version.

**Comment by daviunic** [comment]
Also see issue #14 .
