### ISSUE TITLE
Running the created machine immediately in fullscreen mode

### ISSUE THREAD

**Issue by maximus105** [86Box/86BoxManager#81]
Please add to 86BoxManager the ability to start each created machine at once in fullscreen mode, similar to 86Box.exe -f

**Comment by daviunic** [comment]
Will be considered for version 2.0 when major VM changes are planned.

**Comment by maximus105** [comment]
Is this planned for 86Box Manager v2.0 or has it already been done?

**Comment by daviunic** [comment]
This option will be added to version 2.0, yes.
