### ISSUE TITLE
Taking screenshots is not possible when starting a VM via 86BoxManager

### ISSUE THREAD

**Issue by creopard** [86Box/86BoxManager#83]
If I start a VM using 86BoxManager, it's not possible to take screenshots. There are no new images in the \screenshots folder.
However, starting the same VM (copying the 86box.cfg config file from 86BoxManager), taking screenshots is no problem.

The logfile that 86BoxManager created, sometimes contains just this line (after the initial comment lines):
> Illegal instruction 00008B55 (FF)

However I'm not sure if that's realted to the screenshot issue.

**Comment by daviunic** [comment]
Please provide more information, specifically:
-86Box build
-86Box Manager version
-Host OS version
-Config file for the particular VM where the problem happens

**Comment by creopard** [comment]
- 86Box build: v2.10 build2533
- 86Box Manager version: 1.70
- Host OS version: Windows 10 v1909
- Config file for the particular VM:

```
[Realtek RTL8029AS]
mac = db:53:65

[General]
video_fullscreen_first = 0
confirm_exit = 0

[Machine]
machine = 430vx
cpu = 14
fpu_type = internal
mem_size = 131072
cpu_use_dynarec = 1
time_sync = local

[Video]
gfxcard = virge375_vbe20_pci

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sb16
midi_device = system_midi

[Network]
net_type = slirp
net_card = ne2kpci

[Other peripherals]
hdc = none

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = hd_image.img
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 24
cdrom_01_parameters = 0, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
```

**Comment by daviunic** [comment]
I'm also gonna need the type of 86Box build you're using (regular/debug/dev/optimized), as well as VM name and full path.

**Comment by creopard** [comment]
Sorry, that was apparently my fault, mixing up the 2 "screenshot" folders.
I just noticed, that the screenshots made by 86BoxManager are getting successfully saved in the folder "86box_root\vm-name\screenshots" instead of "86box_root\screenshots".
I simply should have looked into the first folder...
