### ISSUE TITLE
Machine name in title or status area of window [Feature]

### ISSUE THREAD

**Issue by frankmcc** [86Box/86BoxManager#85]
When running multiple systems, especially cloned systems, it is sometimes difficult to determine the system you are working in.  If the machine name was in the title or status area of the window, it would be easier to discern which system is being worked with.

**Comment by daviunic** [comment]
I agree, but this would have to be implemented on the 86Box side too - all the Manager really needs to do is pass it the VM name as a parameter. So you should also open an issue for this on the main repo.

**Comment by frankmcc** [comment]
I just realized this may be an 86 Box issue and not 86Box Manager.  If so I will repost to 86box.
