### ISSUE TITLE
[Bug] VM count info doesn't get updated after configuration in 86Box

### ISSUE THREAD

**Issue by surrodox2001** [86Box/86BoxManager#86]
### Version:
1.7.1 on Windows 7 (.net 4.8)

### Issue: 
The VM count info at the status bar doesn't get updated after a VM configuration in 86Box.

### Ways to reproduce:
1. Configure a VM with 86BoxManager with the configure button and exit 86box.
2. VM count data doesn't get updated as it should.
Example: 
![image](https://user-images.githubusercontent.com/49476868/99496554-7e4e2c00-29af-11eb-8991-fedbd9b07af1.png)

### Afterword:
This issue doesn't happen when starting a VM as usual, the status count gets updated when the VM is running, in configuration or in dialogs (Waiting), or paused.

**Comment by daviunic** [comment]
Can confirm this happens in 1.7.1, looks like I missed the statusbar update for the config event. Will be fixed soon.

**Comment by daviunic** [comment]
Fixed in version 1.7.2.
