### ISSUE TITLE
[BUG] Unable to use hard drive images located on NAS

### ISSUE THREAD

**Issue by solskogen** [86Box/86BoxManager#87]
Hard disk images located on a nas (\\server)  are not saved

**To Reproduce**
1. Add hard disk image located on NAS. Disk image looks like it was added successfully.
2. Press OK
3. Configure VM and go to Hard Disks. The list is now empty.

**Expected behavior**
That the list is not empty :-)

**Environment (please complete the following information):**
 - Host OS: WIndows 10 version 2004
 - 86Box-Optimized-Zen2-32-b83a32cc
 - 86Box Manager Version 1.7.2

**Comment by daviunic** [comment]
This is a problem in the emulator itself, not the Manager. Please submit this issue on [the main emulator repo](https://github.com/86Box/86Box).
