### ISSUE TITLE
86Box updater

### ISSUE THREAD

**Issue by jadasse** [86Box/86BoxManager#90]
**Is your feature request related to a problem? Please describe.**
I notice that 86box gets a new build every few hours in/according to the Jenkins website

**Describe the solution you would like**
I would like it if there was an updater that updates one's build of 86box to the latest version of the same build (e.g., Standard, Dev, Debug)

**Describe alternatives you have considered**
The Dolphin Emulator (emulates GCN/WII (though off-topic)) can perform something similar to what I am talking about.

**Additional context**
Please?

**Comment by daviunic** [comment]
This was discussed as a possibility a long time ago. Perhaps it'll be done in 2.0/a major rewrite, provided the integration with the core emulator doesn't happen before that.

**Comment by jadasse** [comment]
Aight

**Comment by jadasse** [comment]
WinBox has the feature integrated

**Comment by logoffon** [comment]
Except that not everyone wants to use WinBox. I'm still using 86BM as I'm more comfortable with simple design than VirtualBox-like look of WinBox, so adding automatic updating would be still a nice addition.

**Comment by jadasse** [comment]
I know it's not recommended, but when implemented, can 86Box Manager have the option to choose the git path to download a specific 86Box build from? Like PCBox (I know it's not recommended.)?

**Comment by daviunic** [comment]
This program is now in "maintenance-only mode", so no.

**Comment by jadasse** [comment]
> This program is now in "maintenance-only mode", so no.

OK

**Comment by xafero** [comment]
You could try https://github.com/RetBox/86BoxManagerX/releases

**Comment by xafero** [comment]
> > This program is now in "maintenance-only mode", so no.
> 
> OK

You could try https://github.com/RetBox/86BoxManagerX/releases

**Comment by daviunic** [comment]
Not planned, as explained a year ago.
