### ISSUE TITLE
[Feature] Generate new mac address when cloning

### ISSUE THREAD

**Issue by solskogen** [86Box/86BoxManager#96]
When cloning a machine, the clone gets the same mac address as the one you're cloning.

**Comment by daviunic** [comment]
The manager doesn't interact with the VM's configuration in any way. The file is just copied over, any potential adjustments to its contents must be applied manually.

**Comment by solskogen** [comment]
Exactly. It should :-)

**Comment by daviunic** [comment]
Currently there's no plans to add such functionality. A partial rewrite that focuses on under the hood improvements in in the works, but beyond that no major new feature additions are planned.
