### ISSUE TITLE
[Feature] Transform PCem configuration files into usable 86Box VMs

### ISSUE THREAD

**Issue by Lucas-mother3** [86Box/86BoxManager#97]
**Is your feature request related to a problem? Please describe.**
I have a problem to run Chicago 189.  I wanted to migrate those vms to 86Box but recreating them is tedious.

**Describe the solution you'd like**
I wanted to have a feature to use PCem configuration files and translating them into usable VMs

**Describe alternatives you've considered**
You can make some kind of code to translate PCem config files or just use some assets from PCem.

**Comment by daviunic** [comment]
This feature is not planned to be implemented in 2.0.
