### ISSUE TITLE
[BUG] Problem with the "input" section

### ISSUE THREAD

**Issue by Zartan78** [86Box/86BoxManager#98]
**Describe the bug**
The program does not update the "input" section of the config file correctly, in particular the "mouse" subsection.
When changing items from the dropdown menu, the new items are appended to the config file, while the old items are not removed.

**To Reproduce**
1. set mouse input as desired in 86box manager
2. check the config file: there is now a "mouse" section with correct data
3. change the mouse item in 86box manager to another value
4. check the config file again: the new mouse type is added, and the old one is still present.

**Expected behavior**
Changing items in the dropbox menus should replace entries, not simply addding new ones

**Environment (please complete the following information):**
 - windows 10 pro x64
 - tested with several 86box versions, ranging from 2.7 to 3.0.0.3142
 - 86Box Manager Version = 1.7.2
 

This problem creates issues in the guest operating systems (so far i tried both windows 98SE and Windows ME). These include erratic mouse behavior, unresponsive mouse cursor, mouse cursor not present at all.

**Comment by daviunic** [comment]
Not a Manager bug, because the Manager doesn't modify the VM configuration in any way. It simply launches the emulator and that does everything else. So you should file this issue on the main 86Box repo.

**Comment by Zartan78** [comment]
thanks for your reply, I will.
